### ISSUE TITLE
position of HUD error. when actionbar printed

### ISSUE THREAD

**Issue by madebygood** [Ehhthan/HappyHud-Issues#2]
An error that the position of the HUD is deformed when the actionbar is output.

Normal status :
![image](https://user-images.githubusercontent.com/43653581/186144124-830497de-a9cd-499e-9249-bd26396d95aa.png)

Actionbar status : 
![image](https://user-images.githubusercontent.com/43653581/186144257-cad2426f-0f18-4f67-ac07-6f02ae43a51e.png)

You can see that it has moved slightly to the left.

Changing the unicode font makes it even worse.

**Comment by Ehhthan** [comment]
Should be fixed in 0.1.3-SNAPSHOT. Please confirm.

**Comment by Truongvv10** [comment]
Issue still occures for me. See video.
![image](https://user-images.githubusercontent.com/67742370/187092414-7a864af5-a745-4197-99df-82749d023546.png)
@Ehhthan 

https://user-images.githubusercontent.com/67742370/187092374-4e536a47-314e-4b61-919d-589c713169c2.mp4

**Comment by Ehhthan** [comment]
Should be fixed in 0.1.4-SNAPSHOT. Anyone able to verify?

**Comment by klister803** [comment]
sadly it was not fixed, at least using mmocore when the actionbar for skills is printed the hud shifts

**Comment by Ehhthan** [comment]
If you have issues please open a new issue or contact me in the discord.
