### ISSUE TITLE
Hud sometimes shift over when new layouts are added

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#7]
By adding multiple layers, it seems some have a tendency to move all other layers and elements around
Only real consistency ive found are when the `text` property contains a placeholder that is turned into something else.

For example this, where the whistle placeholder is replaced with a unicode tied to a font file (cant use icon as it needs to change with layer)
```yml
mineinabyss-layer:
  layers:
    text:
      text: "%mineinabyss_whistle% %mineinabyss_layer%"
      font: "mineinabyss-outline"
      offset:
        x: 0
        y: 0
```

This one is also one that consistently pushes all other hud elements, so seemingly it must be unicodes in text field?
```yml
mineinabyss-orthbanking-coins:
  layers:
    text:
      text: "%mineinabyss_orthbanking_coins%"
      font: "orthbanking"
      offset:
        x: 0
        y: 0
```

showcase of the to above (middle and bottom command blocks) and other layout that dont affect other layout positions

https://user-images.githubusercontent.com/62521371/186968425-fb77c7dd-faa7-42e9-b4c3-609f8a50ba11.mp4

**Comment by Ehhthan** [comment]
Should be fixed in 0.1.3-SNAPSHOT. Please confirm.

**Comment by Boy0000** [comment]
Seems to still happen on 0.1.3 @Ehhthan 
Below is a 16 pixel image rescaled to height 9 in the font file. 
Having height be the same as pixel fixes it but ofc want to rescale the images

![image](https://user-images.githubusercontent.com/62521371/187067917-effb643a-ca93-47cb-8c5c-38a5c67e58a4.png)

**Comment by Ehhthan** [comment]
Should be fixed in 0.1.4-SNAPSHOT. Anyone able to verify?

**Comment by Boy0000** [comment]
Seems to be fixed indeed 👍 
changed the height of the unicodes font file to = texture height and not and both work as it should

https://user-images.githubusercontent.com/62521371/189668367-11b6be74-26d2-42c6-8a0b-a9cf43542cf5.mp4
